BaSP-TG-05: Superadmin CRUD with MongoDB
BaSP-m2022/alexis-trackgenix-server pull request #14
Opened 2022-05-16 03:56 UTC by martinalbrnz

- Create a superadmin.
- Get all superadmins, by id or with filter.
- Update superadmin by id.
- Delete superadmin by id.
- Validations with Joi.
- Documentation with postman.

2022-05-16 17:39 UTC, FranGutierrez requested changes

2022-05-16 17:39 UTC, FranGutierrez commented on src/validation/super-admins.js
> +    lastName: Joi.string().required(),
Te falto el .min() en lastName

2022-05-16 17:39 UTC, FranGutierrez commented on src/validation/super-admins.js
> +    lastName: Joi.string(),
idem

2022-05-17 01:22 UTC, AlexisPuchetaRR commented on src/controllers/super-admins.js
> +    });
```suggestion
    const stringQuery = await models.SuperAdmin.find({
      firstName: { $regex: new RegExp(firstName || '', 'i') },
      lastName: { $regex: new RegExp(lastName || '', 'i') },
      email: { $regex: new RegExp(email || '', 'i') },
    });
```
por que usamos el RegExp? lo pienso desde el lado de que si estoy buscando algo, y lo ingreso mal, no voy a encontrar nada, por que validaria un get?

2022-05-17 01:24 UTC, AlexisPuchetaRR commented on src/controllers/super-admins.js
> +    const filtered = stringQuery.filter((elem) => ((active === true || active === false)
no entiendo, supongo que te puede llegar active === null o undefined

2022-05-17 01:25 UTC, AlexisPuchetaRR commented on src/controllers/super-admins.js
> +      data: {},
mostremos los errores y el id ingresado

2022-05-17 01:25 UTC, AlexisPuchetaRR commented on src/models/Super-admins.js
> +  { timestamps: true },
y el _id?

2022-05-17 01:30 UTC, AlexisPuchetaRR commented on src/validation/super-admins.js
> +    firstName: Joi.string().min(3).required(),
Al3x1s pasaria como firstName

2022-05-17 01:32 UTC, AlexisPuchetaRR commented on src/validation/super-admins.js
> +    firstName: Joi.string().min(3).required(),
no perder de vista que como string entran nros tambien. Probablemente una RegEx del tipo a-zAZ

2022-05-17 01:46 UTC, martinalbrnz commented on src/controllers/super-admins.js
> +    });
Respecto al new RegExp, es una forma de hacer que pasandole solo una parte del string te devuelva true si esta incluido (todo esto dentro de las query de mongodb). Cuando hice los test, le pasa, por ejemplo, solo una vocal, y te tira todos los nombres que tienen esa vocal (es cierto que no hice validacion de numeros...) Lo mismo con el mail, por ejemplo si le paso un @, como todos los mail tienen arroba, me devuelve todos los usuarios. por otro lado, si es un string vacio (o si no le pase algun campo en el body), el regex de"" da siempre true, o sea que es lo mismo a que no este.
la i como segundo parametro es para hacerlo case insensitive

2022-05-17 01:51 UTC, martinalbrnz commented on src/controllers/super-admins.js
> +    const filtered = stringQuery.filter((elem) => ((active === true || active === false)
Es para forzar que solo se active si me llega true o false. Como desde el json puede llegar siendo bool, no tengo que hacer un parse. Intente hacer la validacion toda adentro de la query pero no habia forma de ingresarlo sin que me tome mal un parametro, entonces opte por el camino que es un poco mas trabajoso pero mas legible para el que tenga que entenderlo despues.
Puedo hacerlo desde la otra forma pero en ese caso si o si hay que pasarle un parametro valido a active (o sea, true o false) y por consiguiente elimino la posibilidad de que solo me filtre por otros campos, ignorando si esta activo o no. De la forma que esta ahi, cuando no es true o false (o no se le pasa parametro) devuelve la lista tal cual entro (desconozco si hay algun equivalente a break para metodos de array).

2022-05-17 01:55 UTC, martinalbrnz commented on src/models/Super-admins.js
> +  { timestamps: true },
Es autogenerado por mongoDB.

2022-05-17 02:34 UTC, martinalbrnz commented on src/validation/super-admins.js
> +    firstName: Joi.string().min(3).required(),
fixed

2022-05-17 03:54 UTC, martinalbrnz commented on src/controllers/super-admins.js
> +    const filtered = stringQuery.filter((elem) => ((active === true || active === false)
Agregado a query en el ultimo commit

2022-05-18 17:01 UTC, AlexisPuchetaRR approved these changes

2022-05-18 17:24 UTC, merged